[build-system]
requires = ["setuptools==78.1.1"]
build-backend = "setuptools.build_meta"

[project]
name = "your-cloud-console"
version = "0.4.0"
description = "Console souveraine your-cloud"
requires-python = ">=3.13"
dependencies = [
  "bcrypt==4.3.0",
  "cffi==2.1.0",
  "cryptography==45.0.5",
  "protobuf==6.31.1",
  "pycparser==3.0",
]

[project.scripts]
your-cloud = "your_cloud_console.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
